#!/bin/bash

version=`cat src/manifest.json | gawk 'match($0, /version":\s*"([0-9\.]+d?)"/, m) { print m[1]; }'`
echo "Packing v$version"

packMozilla() {
	if [ -z "$1" ]; then
		test -f ".creds" || { echo "You must provide credentials for mozilla"; exit 1; }
		source ".creds"
	else
		jwt_issuer="$1"
		jwt_secret="$2"
	fi
	mkdir -p .mozilla-build
	# Copy files to build directory
	cp -r src/* .web-extension-id .mozilla-build/
	# move into directory and perform package and signing
	cd .mozilla-build
	web-ext sign --api-key="$jwt_issuer" --api-secret="$jwt_secret" || { cd ..; rm -R .mozilla-build; exit 1; }
	# move back to root
	cd ..
	# move the new Add-On and ID file back to root
	mkdir -p releases
	mv .mozilla-build/web-ext-artifacts/*.xpi "releases/plutonium-mirror-$version.xpi"
	mv .mozilla-build/.web-extension-id ./.web-extension-id
	# delete the intermediary build directory
	rm -R .mozilla-build
}

packChrome() {
	mkdir -p releases
	cd src
	zip -r "../releases/plutonium-mirror-$version.zip" ./
	cd ..
}


if [ "$1" = "chrome" ]; then
	packChrome
elif [ "$1" = "mozilla" ]; then
	packMozilla $2 $3
elif [ "$1" = "all" ]; then
	packChrome
	packMozilla $2 $3
else
	echo "./pack.sh <chrome|mozilla|all> [mozilla:api-key] [mozilla:api-secret]"
fi

echo "Done Packing v$version"
